---
commonOverlays:
  - name: Remove all annotations with conditions
    query: metadata.annotations
    action: delete
    documentQuery:
      - conditions:
          - query: kind
            value: Service
          - query: metadata.namespace
            value: my-web-page
      - conditions:
          - query: metadata.name
            value: my-service

yamlFiles:
  - name: Set of Kubernetes manifests from upstream
    path: ./manifests
